

# Site Settings
title: 						"EckoThemes"
email: 						"support@ecko.me"
description: 				"Astro is a content focused responsive theme for the Jekyll blogging platform. Available for purchase at ThemeForest.net."
baseurl: 					""
url: 						"http://geeksrik.github.io"
logourl: 					"/assets/img/bloglogo.jpg"		
fa-logo: 					"fa-bookmark-o"
paginate: 					5


# Author Settings
author_name: 				"Srikanth Eswaran"
author_url: 				"http://srik.in"
author_bio: 				"Srikanth Eswaran has seen nearly 35+ years of lifestyle across three generations starting from India being the land of snake charmers to the country becoming the next infrastructural superpower. In this time, he has been through some demanding situations, trials and tribulations which has made him a polished and mature individual who is now poised to handle what life throws at him. His interests lie in writing, discussing online, photography, web-design, software project management and methodologies and automobiles to name a few."
author_email: 				"reachme@srik.in"
author_image: 				"/assets/img/authorimage.jpg"


# Social Settings
twitter_url: 				"http://twitter.com"
facebook_url: 				"http://facebook.com"
github_url:  				"http://github.com"
youtube_url:  				"http://youtube.com"
dribbble_url:  				"http://dribbble.com"
googleplus_url: 			"http://google.com/plus"
instagram_url:  			"http://instagram.com"
pinterest_url:  			"http://pinterest.com"
linkedin_url:  				"http://linkedin.com"


# Theme Settings
theme_disqus_shortname: 	"ecko"
theme_google_comments: 		false
theme_analytics_id: 		"UA-28282324-1"
theme_analytics_domain: 	"ecko.me"
theme_reading_time: 		true
theme_autoload_comments: 	false
theme_always_show_nav: 		false


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					pretty

