# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: "/:title"
relative_permalinks: true

highlighter: pygments

timezone: Asia/Kolkata

# Tagging settings
tag_title_prefix:   "Posts tagged #"
tag_title_suffix:   ""

# Facebook settings
fb_admins:          606660677
avatar:             "/public/images/me_hires.png"
locale:             en_US

# Image settings
image_base:          /public/images/

#fb_appid:           337414769782635

# Setup
title:               Srikanth Eswaran
tagline:             the geek whoz a srik!
url:                 "http://srik.in"
paginate:            4
baseurl:             "/"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Vitaly Repin
  url:               https://twitter.com/vitalyrepin
  email:             vitaly_repin@fsfe.org

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/geeksrik/geeksrik.github.io

# Google sitemap generation
gems:
  - jekyll-sitemap

pages_list:
  About: '/about/'
  Hobby projects: '/hobbies/'
  Tags: '/tags/'
  Feed: '/atom.xml'

